# Generated by Django 4.0.5 on 2022-06-16 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('flag', models.ImageField(upload_to='')),
                ('shield', models.ImageField(upload_to='')),
            ],
        ),
    ]
