# Generated by Django 3.2.8 on 2022-06-17 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerPicture', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('bornDate', models.DateField()),
                ('position', models.CharField(max_length=20)),
                ('shirtNumber', models.FloatField()),
                ('is_starting', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=15),
        ),
    ]
