# Generated by Django 3.2.8 on 2022-06-17 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_name_team_teamname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('birthDate', models.DateField()),
                ('lastName', models.CharField(max_length=20)),
                ('nationality', models.CharField(max_length=20)),
                ('Role', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='player',
            old_name='bornDate',
            new_name='birthDate',
        ),
        migrations.AlterField(
            model_name='team',
            name='flag',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='team',
            name='shield',
            field=models.CharField(max_length=15),
        ),
    ]
